services:
  python:
    build:
      context: "./python"
      dockerfile: "Dockerfile"
    environment:
      - PYTHONUNBUFFERED=1 # Prevents Python from buffering stdout and stderr
      - PYTHONDONTWRITEBYTECODE=1 # Prevents Python from writing .pyc files
      - FASTAPI_ENVIRONMENT=DEVELOPMENT
      - SERVER_IP=0.0.0.0
      - SERVER_PORT=8000
    volumes:
      - "./python:/app"
    ports:
      - "8000:8000"

  # TODO: Do Java không auto load lại khi build thành file .jar
  # webflux:
  #   build:
  #     context: "./demo"
  #     dockerfile: "Dockerfile"
  #   ports:
  #     - "8080:8080"
